name: Get changed applications
description: Get information on changed applications

outputs:
  entry-names:
    description: 'Entry names of changed applications'
    value: ${{ steps.get-entry-names.outputs.entry-names }}

  folders:
    description: 'Root folder paths of changed applications'
    value: ${{ steps.get-folders.outputs.folders }}

  slack-groups:
    description: 'Slack groups of changed applications'
    value: ${{ steps.get-slack-groups.outputs.slack-groups }}

  urls:
    description: 'Root URLs of changed applications'
    value: ${{ steps.get-urls.outputs.urls }}

runs:
  using: composite
  steps:
    - name: Get changed file paths
      shell: bash
      run: |
        echo 'CHANGED_FILE_PATHS<<EOF' >> $GITHUB_ENV
        if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | tr '\n' ' ' >> $GITHUB_ENV
        else
          git diff --name-only origin/master... | tr '\n' ' ' >> $GITHUB_ENV
        fi
        echo 'EOF' >> $GITHUB_ENV

    - name: Get entry names
      id: get-entry-names
      shell: bash
      run: echo ::set-output name=entry-names::$(node script/github-actions/get-changed-apps.js --output-type entry)

    - name: Get folders
      id: get-folders
      shell: bash
      run: echo ::set-output name=folders::$(node script/github-actions/get-changed-apps.js --output-type folder)

    - name: Get Slack groups
      id: get-slack-groups
      shell: bash
      run: echo ::set-output name=slack-groups::$(node script/github-actions/get-changed-apps.js --output-type slack-group)

    - name: Get URLs
      id: get-urls
      shell: bash
      run: echo ::set-output name=urls::$(node script/github-actions/get-changed-apps.js --output-type url)
